#开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8848
  servlet:
    # 应用的访问路径
    context-path: /yqx

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /*
  resources:
    static-locations: classpath:webapp/


# 日志配置
logging:
  level:
    com.example: debug
  file:
    path: logs

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.example.model
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

