server:
  port: 8080
  servlet:
    context-path: /maven

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true

#docxPath: D://home//person-project//helloworld.docx
docxPath: /home/person-project/helloworld.docx
