server:
  port: 8080
  servlet:
    context-path: /maven

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  mvc:
    servlet:
      load-on-startup: 1

docxPath: /home/person-project/helloworld.docx
picPath: /home/person-project/avatar.png
templatePath: /home/person-project/template.docx
outPath: /home/person-project/out.docx