server:
  port: 8080
  servlet:
    context-path: /maven

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  mvc:
    servlet:
      load-on-startup: 1

picPath: /home/person-project/avatar.png
template01Path: /home/person-project/template01.docx
template01OutPath: /home/person-project/template01_out.docx
template02Path: /home/person-project/template02.docx
template02outPath: /home/person-project/template02_out.docx