server:
  port: 8080
  servlet:
    context-path: /maven

spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true

docxPath: /home/person-project/helloworld.docx
picPath: /home/person-project/avatar.png
